# Generated by Django 5.0 on 2023-12-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA')], max_length=10)),
                ('sem', models.CharField(choices=[('Sem 1', 'Sem 1'), ('Sem 2', 'Sem 2'), ('Sem 3', 'Sem 3'), ('Sem 4', 'Sem 4'), ('Sem 5', 'Sem 5'), ('Sem 6', 'Sem 6')], max_length=10)),
                ('content', models.TextField(max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='Notes')),
            ],
        ),
    ]
