# Generated by Django 5.0 on 2024-01-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA')], default='BCA', max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='sem',
            field=models.CharField(choices=[('Sem 1', 'Sem 1'), ('Sem 2', 'Sem 2'), ('Sem 3', 'Sem 3'), ('Sem 4', 'Sem 4'), ('Sem 5', 'Sem 5'), ('Sem 6', 'Sem 6')], default='Sem 1', max_length=10),
        ),
    ]
